# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/maurizioberta/Documents/Max\ 8/Packages/tsp/source/min-api/test/mock/CMakeLists.txt))

/Users/maurizioberta/Documents/Max\ 8/Packages/tsp/source/projects/dynamictsp/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/Cellar/cmake/3.24.3/bin/cmake -H/Users/maurizioberta/Documents/Max\ 8/Packages/tsp/source/projects/dynamictsp -B/Users/maurizioberta/Documents/Max\ 8/Packages/tsp/source/projects/dynamictsp
